
#ifndef HAL_KPD_KPD_PRIVATE_H_
#define HAL_KPD_KPD_PRIVATE_H_

#define KPD_PINS 			{KPD_COL1,KPD_COL2,KPD_COL3,KPD_COL4,KPD_ROW1,KPD_ROW2,KPD_ROW3,KPD_ROW4}

#define ROW_START_INDEX		4

#endif
